spring:
  application:
    name: DoraSync
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/dora}
    username: ${DATASOURCE_USERNAME:dora}
    password: ${DATASOURCE_PASSWORD:dora}
  threads:
    virtual:
      enabled: true

dora-sync:
  scheduled-job-enqueuer:
    fixed-rate: 1m
  stale-job-reaper:
    fixed-rate: 1m
  job-step-worker:
    fixed-rate: 1m
    batch-size: 50
