spring:
  application:
    name: DoraSync
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://homeserver:8059/dora}
    username: ${DATASOURCE_USERNAME:dora}
    password: ${DATASOURCE_PASSWORD:dora}
  threads:
    virtual:
      enabled: true

dora-sync:
  github:
    graphql-url: ${GITHUB_GRAPHQL_URL:https://api.github.com/graphql}
    token: ${GITHUB_TOKEN}
  scheduled-job-enqueuer:
    fixed-rate: 1m
  stale-job-reaper:
    fixed-rate: 1m
  job-step-worker:
    fixed-rate: 1m
    batch-size: 50
